### ISSUE TITLE
support git cloning over https as well

### ISSUE THREAD

**Issue by abraxxa** [tadzik/rakudobrew#36]
As some people require git: and some https: a command line parameter would be the best solution with maybe a config file or env var to not have to type it every time if you differ from the default.

**Comment by tadzik** [comment]
Hmm, what if it tried the default and if that fails tried using the other? Like "cloning via git:// failed, trying https://...."?

**Comment by ravenhall** [comment]
Either of those solutions would be acceptable. I had to modify rakudobrew manually to use https instead of git due to firewall restrictions.

**Comment by book** [comment]
For the record, I also patched `rakudbrew` to use http because of firewall issues.

Since `rakudobrew` does not really handles command line options, but already has a environment variable for `GIT_BINARY`, maybe a `GITHUB_PROTO` environment variable (possible values: `git`, `http`, `https`, `ssh`) would be sufficient.

**Comment by tadzik** [comment]
Does no checking on the protocol variable, but it at least handles git and https. For further improvements, patches welcome :)
